# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd0749fd1c9c9daf04a7991601982f96ce7de86ffcba19429fd964df9c9269ca23814319b1c0022bc866094ab23c3a9c2a0006353dcc239cbe41a990d52c7ae7

test:
  secret_key_base: 05d0991fab5fa405b6e6a238412c40d1d1aa4609510128a266223dd2a830f30ebccadce524d37e7720652ffc048478a0600834e25c221b69ca0d20c7a45fea2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
